### ISSUE TITLE
Basic Unicode support

### ISSUE THREAD

**Issue by lain-dono** [leontoeides/indicium#2]
Strings in rust contain utf-8 encoded characters. Which is a variable character length encoding. So

```rust
let mut index = indicium::simple::SearchIndex::<usize>::default();
index.search("лол"); // lol in Cyrillic
```

causes an error

```
thread 'main' panicked at indicium-0.6.1/src/simple/internal/strsim/strsim_context_autocomplete.rs:51:30:
byte index 3 is not a char boundary; it is inside 'о' (bytes 2..4) of `лол`
```

Here's an example of an internal representation:

```
lol: [108, 111, 108]
лол: [208, 187, 208, 190, 208, 187]
```

**Comment by leontoeides** [comment]
Thank you for reporting this @lain-dono. This has been corrected, I've added a test, and a new version has been published.
